### ISSUE TITLE
Parse more ping information

### ISSUE THREAD

**Issue by MoshiMoshi0** [seunomosowon/TA-connectivity#1]
Recently found this app and im finding it quite useful but it seems that pinger.py does not parse all of rtt/packet information.

For windows it just parses average rtt and packet loss. For linux it parses packet loss and time that the ping command took, not the average rtt, which is a bug itself caused by using small packet size (the ping command does not output full rtt information for small packet size).

So I tweaked the code to include full rtt information (avg, min, max, mdev) and packet information (sent, received, loss).
You can find new pinger.py file [here](http://pastebin.com/ZKUeWZAL).
The code is only tested on linux. Forgive me any bugs as I dont use python and I dont have splunk dev setup.

I hope you will incorporate those changes. If needed I can make a pull request .

**Comment by seunomosowon** [comment]
Nice!
I'll incorporate the changes and see if I can test on windows/Mac.

I've only heard from one other person, but it's good to hear that you found
it useful.

Thanks again.
